declare const styles: {
	readonly actionButtonFill: string;
	readonly bottomLeft: string;
	readonly bottomRight: string;
	readonly branding: string;
	readonly brandingLink: string;
	readonly card: string;
	readonly content: string;
	readonly description: string;
	readonly footer: string;
	readonly footerColumn: string;
	readonly footerFill: string;
	readonly footerSubGroup: string;
	readonly footerSubGroupColumn: string;
	readonly footerSubGroupFill: string;
	readonly header: string;
	readonly title: string;
	readonly topLeft: string;
	readonly topRight: string;
	readonly widget: string;
};
export = styles;
