declare const styles: {
	readonly acceptButton: string;
	readonly actionButtonFill: string;
	readonly bannerHidden: string;
	readonly bannerVisible: string;
	readonly bottomLeft: string;
	readonly bottomRight: string;
	readonly card: string;
	readonly cardShell: string;
	readonly customizeButton: string;
	readonly description: string;
	readonly footer: string;
	readonly footerColumn: string;
	readonly footerFill: string;
	readonly footerSubGroup: string;
	readonly footerSubGroupColumn: string;
	readonly footerSubGroupFill: string;
	readonly header: string;
	readonly overlay: string;
	readonly overlayHidden: string;
	readonly overlayVisible: string;
	readonly rejectButton: string;
	readonly root: string;
	readonly title: string;
	readonly topLeft: string;
	readonly topRight: string;
};
export = styles;
