declare const styles: {
	readonly bannerEnterActive: string;
	readonly bannerEnterFrom: string;
	readonly bannerEnterTo: string;
	readonly bannerHidden: string;
	readonly bannerLeaveActive: string;
	readonly bannerLeaveFrom: string;
	readonly bannerLeaveTo: string;
	readonly bannerVisible: string;
	readonly card: string;
	readonly cardShell: string;
	readonly description: string;
	readonly footer: string;
	readonly header: string;
	readonly overlay: string;
	readonly overlayEnterActive: string;
	readonly overlayEnterFrom: string;
	readonly overlayEnterTo: string;
	readonly overlayHidden: string;
	readonly overlayLeaveActive: string;
	readonly overlayLeaveFrom: string;
	readonly overlayLeaveTo: string;
	readonly overlayVisible: string;
	readonly root: string;
	readonly title: string;
};
export = styles;
