declare const styles: {
	readonly acceptButton: string;
	readonly bannerHidden: string;
	readonly bannerVisible: string;
	readonly card: string;
	readonly cardShell: string;
	readonly customizeButton: string;
	readonly description: string;
	readonly footer: string;
	readonly footerButtonGroup: string;
	readonly footerSpacer: string;
	readonly header: string;
	readonly legitimateInterestNotice: string;
	readonly overlay: string;
	readonly overlayHidden: string;
	readonly overlayVisible: string;
	readonly partnersLink: string;
	readonly privacyLink: string;
	readonly purposeList: string;
	readonly rejectButton: string;
	readonly root: string;
	readonly title: string;
};
export = styles;
